DROP TABLE OMTAUDIT;
CREATE TABLE OMTAUDIT
(
  ID VARCHAR2(36) NOT NULL
, AUDITID VARCHAR2(36)
, RULETYPE VARCHAR2(36)
, RULEGUID VARCHAR2(36)
, RULENAME VARCHAR2(150)
, DEVELOPER VARCHAR2(255)
, SOURCEREGION VARCHAR2(20)
, SOURCEVERSION VARCHAR2(20)
, TARGETREGION VARCHAR2(20)
, TARGETVERSION VARCHAR2(20)
, MIGRATEDBY VARCHAR2(150)
, MIGRATEDON TIMESTAMP
, REASON VARCHAR2(500)
, QAMIGRATED CHAR(1)
, QAMIGRATEDON TIMESTAMP
, QAMIGRATEDBY VARCHAR2(255)
, UATMIGRATED CHAR(1)
, UATMIGRATEDON TIMESTAMP
, UATMIGRATEDBY VARCHAR2(255)
, PERFMIGRATED CHAR(1)
, PERFMIGRATEDON TIMESTAMP
, PERFMIGRATEDBY VARCHAR2(255)
, PRODMIGRATED CHAR(1)
, PRODMIGRATEDON TIMESTAMP
, PRODMIGRATEDBY VARCHAR2(255)
,PRIMARY KEY (ID )
);


DROP TABLE OMTUSER;
CREATE TABLE OMTUSER 
   (	USERID VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	LOGINID VARCHAR2(155 BYTE) NOT NULL ENABLE, 
	FIRSTNAME VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	LASTNAME VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	EMAIL VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	PASSWORD VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	ENABLED NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	PRIMARY KEY (USERID), 
	CONSTRAINT OMTUSER_UK_LOGIN UNIQUE (LOGINID)
    );

DROP TABLE OMTROLE;    
CREATE  TABLE OMTROLE (
  ROLEID VARCHAR(36) NOT NULL,
  ROLENAME VARCHAR(255),
  ROLEDESCRIPTION VARCHAR(255),
  PRIMARY KEY (ROLEID)
  );
  
DROP TABLE OMTUSERROLE;
CREATE TABLE OMTUSERROLE (
  USER_ROLE_ID VARCHAR(36) NOT NULL,
  USERID VARCHAR(36) NOT NULL,
  ROLEID VARCHAR(36) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  CONSTRAINT OMTUSER_UK_USRL UNIQUE (ROLEID,USERID)
  );
  
 DROP TABLE OMTREGION;
 CREATE TABLE "OMTREGION" 
   (	
	"ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"IDENTIFIER" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"DESTINATION" NUMBER, 
	"NONIVS" NUMBER, 
	"UPPERREGION" NUMBER, 
	"SANDBOX" NUMBER, 
	"PASHOST" VARCHAR2(150 BYTE), 
	"PASPORT" NUMBER, 
	"PASUSER" VARCHAR2(150 BYTE), 
	"PASPASSWORD" VARCHAR2(150 BYTE), 
	"IVSHOST" VARCHAR2(150 BYTE), 
	"IVSPORT" NUMBER, 
	"IVSUSER" VARCHAR2(150 BYTE), 
	"IVSPASSWORD" VARCHAR2(150 BYTE), 
	"PASSID" VARCHAR2(150 BYTE), 
	"IVSSID" VARCHAR2(150 BYTE), 
	 CONSTRAINT "OMTREGION_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "OMTUSER_UK_REGION" UNIQUE ("IDENTIFIER")
   );
 
 DROP TABLE OMTUSERREGION;
 CREATE TABLE "OMTUSERREGION" 
   (
    "ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"REGIONID" VARCHAR2(36 BYTE), 
	"USERID" VARCHAR2(36 BYTE), 
	 CONSTRAINT "OMTUSERREGION_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "OMTUSER_UK_UR" UNIQUE ("REGIONID","USERID")
  )

DROP SEQUENCE AUDIT_ID_SEQ;
CREATE SEQUENCE AUDIT_ID_SEQ
START WITH 1
MAXVALUE  9999999999
INCREMENT  BY 1
CACHE 20;

CREATE OR REPLACE FUNCTION NEXT_AUDIT_ID RETURN VARCHAR2
  AS
  BEGIN
  RETURN('AUDIT'||TO_CHAR(AUDIT_ID_SEQ.NEXTVAL,'FM0000000000') );
  END;
/

DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ
START WITH 1
MAXVALUE  9999999999
INCREMENT  BY 1
CACHE 20;

CREATE OR REPLACE FUNCTION NEXT_USER_ID RETURN VARCHAR2
  AS
  BEGIN
  RETURN('USER'||TO_CHAR(USER_ID_SEQ.NEXTVAL,'FM0000000000') );
  END;
/

DROP SEQUENCE ROLE_ID_SEQ;
CREATE SEQUENCE ROLE_ID_SEQ
START WITH 1
MAXVALUE  9999999999
INCREMENT  BY 1
CACHE 20;

CREATE OR REPLACE FUNCTION NEXT_ROLE_ID RETURN VARCHAR2
  AS
  BEGIN
  RETURN('ROLE'||TO_CHAR(ROLE_ID_SEQ.NEXTVAL,'FM0000000000') );
  END;
/

DROP SEQUENCE USER_ROLE_ID_SEQ;
CREATE SEQUENCE USER_ROLE_ID_SEQ
START WITH 1
MAXVALUE  9999999999
INCREMENT  BY 1
CACHE 20;

CREATE OR REPLACE FUNCTION NEXT_USER_ROLE_ID RETURN VARCHAR2
  AS
  BEGIN
  RETURN('USERROLE'||TO_CHAR(USER_ROLE_ID_SEQ.NEXTVAL,'FM0000000000') );
  END;
/