INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (1, 'Jhon', 'Doe', 32);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (2, 'Sam', 'Donovan', 44);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (3, 'Sergei', 'Bubka', 45);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (4, 'Peter', 'Russel', 37);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (5, 'Arnold', 'Wright', 39);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (6, 'Kyle', 'Houge', 24);
INSERT INTO EMPLOYEE(ID, FNAME, LNAME, AGE) VALUES (7, 'Samatha', 'Pit', 53);